version: "3" 
services:
 mariadb:
  container_name: mariadb
  networks:
   - inception
  build: requirements/mariadb
  env_file: .env
  volumes:
   - ~/data/mariadb:/var/lib/mysql
  restart: unless-stopped
  expose:
   - "3306"
 nginx:
  container_name: nginx
  volumes:
   - ~/data/wordpress:/var/www/wordpress
  networks:
   - inception
  depends_on:
   - wordpress
  build: requirements/nginx
  env_file: .env
  ports:
   - "443:443"
  restart: on-failure
 wordpress:
  container_name: wordpress
  env_file: .env
  volumes:
   - ~/data/wordpress:/var/www/wordpress
  networks:
   - inception 
  build: requirements/wordpress
  depends_on:
   - mariadb
  restart: on-failure
  expose: 
   - "9000"
volumes:
 wordpress:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/${USER}/data/wordpress'
 mariadb:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/${USER}/data/mariadb'
networks:
 inception:
  driver: bridge

