version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb # Le nom du container
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception # à quel network il appartient
    build: 
      context: requirements/mariadb # ou se trouve son Dockerfile
      dockerfile: Dockerfile
    env_file: .env  # le fichier d'environnement pour transmettre les variables
    restart: on-failure # "on-failure", container will be restarted 
    expose:
      - "3306"

  nginx:           # with TLSv.1.2
    image: nginx
    container_name: nginx # name of the container
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:    # wordpress will be started after mariadb
      - mariadb
    restart: on-failure
    expose: 
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/wordpress' #Ou stocker le dossier sur l'ordi en local
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/mariadb'



#network part
networks:
    inception:
      driver: bridge

